// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {bulk_file_processing} from '../models';
import {advanced_file_operations} from '../models';

export function GetBulkProcessingJob(arg1:string):Promise<bulk_file_processing.ProcessingJob>;

export function ProcessBulkFiles(arg1:advanced_file_operations.BulkProcessingRequest):Promise<advanced_file_operations.BulkProcessingResponse>;
