// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetBulkProcessingJob(arg1) {
  return window['go']['advanced_file_operations']['AdvancedFileOperations']['GetBulkProcessingJob'](arg1);
}

export function ProcessBulkFiles(arg1) {
  return window['go']['advanced_file_operations']['AdvancedFileOperations']['ProcessBulkFiles'](arg1);
}
