// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {action} from '../models';
import {context} from '../models';
import {namer} from '../models';
import {patterns} from '../models';
import {config} from '../models';
import {logger} from '../models';

export function DeleteProfile(arg1:string):Promise<void>;

export function GetActionInfo():Promise<Array<action.Info>>;

export function GetContext():Promise<context.Context>;

export function GetNamerInfo():Promise<Array<namer.Info>>;

export function GetPatternInfo():Promise<Array<patterns.PatternInfo>>;

export function LoadProfiles():Promise<Record<string, config.Config>>;

export function Logf(arg1:logger.LogLevel,arg2:string,arg3:Array<any>):Promise<void>;

export function SaveProfile(arg1:string,arg2:config.Config):Promise<void>;

export function SelectActionDirectory():Promise<string>;

export function SelectDirectory():Promise<string>;

export function StartWatching(arg1:config.Config):Promise<void>;

export function StopWatching():Promise<void>;
