// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteProfile(arg1) {
  return window['go']['main']['App']['DeleteProfile'](arg1);
}

export function GetActionInfo() {
  return window['go']['main']['App']['GetActionInfo']();
}

export function GetContext() {
  return window['go']['main']['App']['GetContext']();
}

export function GetNamerInfo() {
  return window['go']['main']['App']['GetNamerInfo']();
}

export function GetPatternInfo() {
  return window['go']['main']['App']['GetPatternInfo']();
}

export function LoadProfiles() {
  return window['go']['main']['App']['LoadProfiles']();
}

export function Logf(arg1, arg2, arg3) {
  return window['go']['main']['App']['Logf'](arg1, arg2, arg3);
}

export function SaveProfile(arg1, arg2) {
  return window['go']['main']['App']['SaveProfile'](arg1, arg2);
}

export function SelectActionDirectory() {
  return window['go']['main']['App']['SelectActionDirectory']();
}

export function SelectDirectory() {
  return window['go']['main']['App']['SelectDirectory']();
}

export function StartWatching(arg1) {
  return window['go']['main']['App']['StartWatching'](arg1);
}

export function StopWatching() {
  return window['go']['main']['App']['StopWatching']();
}
